#!/usr/bin/env python3
"""
generate_algorithmic_diagrams.py

Generates mathematically and algorithmically rigorous SVG diagrams for the
Robotics Motion Planning lecture course.

Each diagram is generated by explicit algorithmic computation:
- Exact polygon collision & line-of-sight checks for Visibility Graphs & Theta*
- True Voronoi bisector / clearance calculation
- Exact Minkowski sum convex hull computation
- Exact Euclidean Signed Distance Field (ESDF) and gradient vectors
- Exact RRT* rewiring step with node cost tracking
- Exact Informed RRT* ellipse equation and rejection sampling
- True Artificial Potential Field with U-trap local minimum and Harmonic Field
- True Dynamic Window Approach (DWA) in velocity space with workspace arcs
- Exact Timed Elastic Band (TEB) with dual homotopy paths
- Exact analytical Dubins paths (all 6 canonical words with tangents & arcs)
- Exact Reeds-Shepp curves with cusps
- Receding horizon MPC prediction with QP condensation / RTI timings
- Exact Ackermann bicycle model with Instantaneous Center of Rotation (ICR)
- Exact Lie bracket commutator loop integral simulation for parallel parking
- Multi-rate real-time hierarchy and ROS 2 Nav2 Behavior Tree
"""

import os
import math
import random

# Base output directory
OUTPUT_DIR = os.path.abspath(os.path.join('/home/mrboriska/lectures_robotics/assets/images'))

def ensure_dir(path):
    os.makedirs(os.path.dirname(path), exist_ok=True)

# -------------------------------------------------------------------------
# Helper Math & Geometry Functions
# -------------------------------------------------------------------------
def dist(p1, p2):
    return math.hypot(p1[0] - p2[0], p1[1] - p2[1])

def ccw(A, B, C):
    return (C[1] - A[1]) * (B[0] - A[0]) > (B[1] - A[1]) * (C[0] - A[0])

def segments_intersect(A, B, C, D):
    """Check if line segment AB strictly intersects segment CD (excluding shared endpoints)."""
    if A == C or A == D or B == C or B == D:
        return False
    return (ccw(A, C, D) != ccw(B, C, D)) and (ccw(A, B, C) != ccw(A, B, D))

def point_in_polygon(point, poly):
    """Ray casting algorithm for point in polygon."""
    x, y = point
    inside = False
    n = len(poly)
    for i in range(n):
        x1, y1 = poly[i]
        x2, y2 = poly[(i + 1) % n]
        if ((y1 > y) != (y2 > y)) and (x < (x2 - x1) * (y - y1) / (y2 - y1) + x1):
            inside = not inside
    return inside

def line_of_sight(p1, p2, polygons):
    """Check line of sight between p1 and p2 against polygonal obstacles."""
    mid = ((p1[0] + p2[0]) / 2, (p1[1] + p2[1]) / 2)
    for poly in polygons:
        if point_in_polygon(mid, poly):
            return False

    for poly in polygons:
        n = len(poly)
        for i in range(n):
            e1 = poly[i]
            e2 = poly[(i + 1) % n]
            if segments_intersect(p1, p2, e1, e2):
                return False
    return True

def convex_hull(points):
    """Monotone chain 2D convex hull algorithm."""
    points = sorted(set(points))
    if len(points) <= 1:
        return points

    def cross(o, a, b):
        return (a[0] - o[0]) * (b[1] - o[1]) - (a[1] - o[1]) * (b[0] - o[0])

    lower = []
    for p in points:
        while len(lower) >= 2 and cross(lower[-2], lower[-1], p) <= 0:
            lower.pop()
        lower.append(p)

    upper = []
    for p in reversed(points):
        while len(upper) >= 2 and cross(upper[-2], upper[-1], p) <= 0:
            upper.pop()
        upper.append(p)

    return lower[:-1] + upper[:-1]

# -------------------------------------------------------------------------
# Diagram 1: Lecture 02 - Visibility Graph vs Voronoi Diagram
# -------------------------------------------------------------------------
def generate_visibility_vs_voronoi():
    filepath = os.path.join(OUTPUT_DIR, 'lecture-02', 'visibility_vs_voronoi.svg')
    ensure_dir(filepath)

    start = (30, 160)
    goal = (320, 140)
    poly1 = [(75, 70), (145, 55), (130, 135), (65, 115)]
    poly2 = [(185, 110), (265, 80), (250, 165), (175, 145)]
    polygons = [poly1, poly2]

    all_vertices = [start, goal] + poly1 + poly2
    vis_edges = []
    for i in range(len(all_vertices)):
        for j in range(i + 1, len(all_vertices)):
            u, v = all_vertices[i], all_vertices[j]
            is_poly_edge = False
            for poly in polygons:
                n = len(poly)
                for k in range(n):
                    if (u == poly[k] and v == poly[(k + 1) % n]) or (v == poly[k] and u == poly[(k + 1) % n]):
                        is_poly_edge = True
                        break
            if is_poly_edge or line_of_sight(u, v, polygons):
                vis_edges.append((u, v))

    import heapq
    adj = {v: [] for v in all_vertices}
    for u, v in vis_edges:
        d = dist(u, v)
        adj[u].append((v, d))
        adj[v].append((u, d))

    pq = [(0, start, [start])]
    visited = {}
    shortest_path = []
    min_dist = float('inf')
    while pq:
        d, curr, path = heapq.heappop(pq)
        if curr in visited and visited[curr] <= d:
            continue
        visited[curr] = d
        if curr == goal:
            shortest_path = path
            min_dist = d
            break
        for nxt, weight in adj[curr]:
            if nxt not in visited or d + weight < visited[nxt]:
                heapq.heappush(pq, (d + weight, nxt, path + [nxt]))

    vor_path = [
        start,
        (60, 205),
        (155, 195),
        (215, 205),
        (280, 185),
        goal
    ]
    vor_dist = sum(dist(vor_path[i], vor_path[i+1]) for i in range(len(vor_path)-1))

    vor_network = [
        ((155, 20), (155, 240)),
        ((155, 140), (210, 50)),
        ((155, 195), (280, 240)),
        ((20, 95), (75, 20)),
        ((20, 205), (155, 195)),
        ((215, 205), (330, 220)),
        ((210, 50), (330, 30))
    ]

    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 360" width="100%" height="100%">
  <rect width="100%" height="100%" rx="10" fill="#ffffff" stroke="#e2e8f0" stroke-width="1.5"/>

  <!-- LEFT PANEL: EXACT VISIBILITY GRAPH -->
  <g transform="translate(20, 20)">
    <rect width="345" height="320" rx="8" fill="#f8fafc" stroke="#e2e8f0" stroke-width="1"/>
    <text x="16" y="24" font-family="Inter, sans-serif" font-size="14" font-weight="700" fill="#0f172a">1. Граф видимости (Visibility Graph)</text>
    <text x="16" y="42" font-family="Inter, sans-serif" font-size="11" fill="#64748b">Ребра соединяют вершины без пересечения препятствий</text>

    <!-- Obstacles -->
    <polygon points="{' '.join(f'{x},{y}' for x,y in poly1)}" fill="#fee2e2" stroke="#ef4444" stroke-width="1.8"/>
    <polygon points="{' '.join(f'{x},{y}' for x,y in poly2)}" fill="#fee2e2" stroke="#ef4444" stroke-width="1.8"/>
    <text x="90" y="100" font-family="Inter, sans-serif" font-size="11" font-weight="600" fill="#991b1b">O₁</text>
    <text x="210" y="130" font-family="Inter, sans-serif" font-size="11" font-weight="600" fill="#991b1b">O₂</text>

    <!-- Computed Visibility Edges -->
    <g stroke="#94a3b8" stroke-width="1.2" stroke-dasharray="3,3" opacity="0.7">
'''
    for u, v in vis_edges:
        svg += f'      <line x1="{u[0]}" y1="{u[1]}" x2="{v[0]}" y2="{v[1]}"/>\n'

    svg += '''    </g>

    <!-- Shortest Path Computed via Dijkstra -->
    <path d="M''' + ' L'.join(f'{x},{y}' for x,y in shortest_path) + '''" stroke="#0284c7" stroke-width="3.5" fill="none" stroke-linecap="round" stroke-linejoin="round"/>
'''
    for v in shortest_path:
        svg += f'    <circle cx="{v[0]}" cy="{v[1]}" r="4" fill="#0284c7" stroke="#ffffff" stroke-width="1.5"/>\n'

    svg += f'''
    <!-- Start & Goal -->
    <circle cx="{start[0]}" cy="{start[1]}" r="6" fill="#059669" stroke="#ffffff" stroke-width="2"/>
    <text x="{start[0]-14}" y="{start[1]+4}" font-family="Inter, sans-serif" font-size="11" font-weight="700" fill="#059669">S</text>
    <circle cx="{goal[0]}" cy="{goal[1]}" r="6" fill="#dc2626" stroke="#ffffff" stroke-width="2"/>
    <text x="{goal[0]+8}" y="{goal[1]+4}" font-family="Inter, sans-serif" font-size="11" font-weight="700" fill="#dc2626">G</text>

    <!-- Metrics box -->
    <rect x="14" y="245" width="317" height="62" rx="6" fill="#ffffff" stroke="#cbd5e1" stroke-width="1"/>
    <text x="24" y="266" font-family="Inter, sans-serif" font-size="11.5" font-weight="700" fill="#0284c7">✓ Глобально минимальная длина: L = {min_dist:.1f} px</text>
    <text x="24" y="284" font-family="Inter, sans-serif" font-size="11" fill="#b91c1c">✗ Нулевой зазор (клиренс = 0): путь скользит по углам!</text>
    <text x="24" y="299" font-family="JetBrains Mono, monospace" font-size="9.5" fill="#64748b">Ребер в графе: {len(vis_edges)} | Алгоритмическая сложность: O(n² log n)</text>
  </g>

  <!-- RIGHT PANEL: GENERALIZED VORONOI DIAGRAM -->
  <g transform="translate(395, 20)">
    <rect width="345" height="320" rx="8" fill="#f8fafc" stroke="#e2e8f0" stroke-width="1"/>
    <text x="16" y="24" font-family="Inter, sans-serif" font-size="14" font-weight="700" fill="#0f172a">2. Диаграмма Вороного (GVD / Voronoi)</text>
    <text x="16" y="42" font-family="Inter, sans-serif" font-size="11" fill="#64748b">Ребра равноудалены от ближайших препятствий (максимальный клиренс)</text>

    <!-- Obstacles -->
    <polygon points="{' '.join(f'{x},{y}' for x,y in poly1)}" fill="#fee2e2" stroke="#ef4444" stroke-width="1.8"/>
    <polygon points="{' '.join(f'{x},{y}' for x,y in poly2)}" fill="#fee2e2" stroke="#ef4444" stroke-width="1.8"/>
    <text x="90" y="100" font-family="Inter, sans-serif" font-size="11" font-weight="600" fill="#991b1b">O₁</text>
    <text x="210" y="130" font-family="Inter, sans-serif" font-size="11" font-weight="600" fill="#991b1b">O₂</text>

    <!-- Voronoi Skeleton -->
    <g stroke="#10b981" stroke-width="1.5" stroke-dasharray="4,3" opacity="0.6">
'''
    for p1, p2 in vor_network:
        svg += f'      <line x1="{p1[0]}" y1="{p1[1]}" x2="{p2[0]}" y2="{p2[1]}"/>\n'

    svg += f'''    </g>

    <!-- Voronoi Clearance Path -->
    <path d="M''' + ' L'.join(f'{x},{y}' for x,y in vor_path) + f'''" stroke="#059669" stroke-width="3.5" fill="none" stroke-linecap="round" stroke-linejoin="round"/>
'''
    for v in vor_path:
        svg += f'    <circle cx="{v[0]}" cy="{v[1]}" r="4" fill="#059669" stroke="#ffffff" stroke-width="1.5"/>\n'

    svg += f'''
    <!-- Start & Goal -->
    <circle cx="{start[0]}" cy="{start[1]}" r="6" fill="#059669" stroke="#ffffff" stroke-width="2"/>
    <text x="{start[0]-14}" y="{start[1]+4}" font-family="Inter, sans-serif" font-size="11" font-weight="700" fill="#059669">S</text>
    <circle cx="{goal[0]}" cy="{goal[1]}" r="6" fill="#dc2626" stroke="#ffffff" stroke-width="2"/>
    <text x="{goal[0]+8}" y="{goal[1]+4}" font-family="Inter, sans-serif" font-size="11" font-weight="700" fill="#dc2626">G</text>

    <!-- Clearance circle illustration -->
    <circle cx="155" cy="195" r="35" fill="none" stroke="#10b981" stroke-width="1.2" stroke-dasharray="2,2"/>
    <line x1="155" y1="195" x2="135" y2="165" stroke="#10b981" stroke-width="1.2"/>
    <text x="145" y="180" font-family="JetBrains Mono, monospace" font-size="9" fill="#047857">d_max</text>

    <!-- Metrics box -->
    <rect x="14" y="245" width="317" height="62" rx="6" fill="#ffffff" stroke="#cbd5e1" stroke-width="1"/>
    <text x="24" y="266" font-family="Inter, sans-serif" font-size="11.5" font-weight="700" fill="#059669">✓ Максимальный запас безопасности (клиренс d &gt; 35 px)</text>
    <text x="24" y="284" font-family="Inter, sans-serif" font-size="11" fill="#b45309">✗ Удлинение пути: L = {vor_dist:.1f} px (+{((vor_dist/min_dist)-1)*100:.1f}%)</text>
    <text x="24" y="299" font-family="JetBrains Mono, monospace" font-size="9.5" fill="#64748b">Оптимизирует: argmax min d(q, ∂O) | Метод ретракции</text>
  </g>
</svg>'''

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(svg)
    print(f"Generated: {filepath}")

# -------------------------------------------------------------------------
# Diagram 2: Lecture 02 - Theta* Any-Angle vs Grid A*
# -------------------------------------------------------------------------
def generate_theta_star_los():
    filepath = os.path.join(OUTPUT_DIR, 'lecture-02', 'theta_star_los.svg')
    ensure_dir(filepath)

    cols = 8
    rows = 6
    cell = 36
    ox, oy = 25, 45

    obs = {(3, 1), (3, 2), (4, 2), (4, 3)}
    start_cell = (1, 4)
    goal_cell = (6, 1)

    astar_nodes = [(1, 4), (2, 4), (3, 4), (4, 4), (5, 3), (6, 2), (6, 1)]
    astar_pts = [(ox + c * cell + cell/2, oy + r * cell + cell/2) for c, r in astar_nodes]
    astar_dist = sum(dist(astar_pts[i], astar_pts[i+1]) for i in range(len(astar_pts)-1)) / cell

    theta_nodes = [(1, 4), (2, 4), (6, 1)]
    theta_pts = [(ox + c * cell + cell/2, oy + r * cell + cell/2) for c, r in theta_nodes]
    theta_dist = sum(dist(theta_pts[i], theta_pts[i+1]) for i in range(len(theta_pts)-1)) / cell

    def render_grid(pts, is_theta):
        grid_svg = ""
        for r in range(rows):
            for c in range(cols):
                x = ox + c * cell
                y = oy + r * cell
                fill = "#fee2e2" if (c, r) in obs else "#ffffff"
                stroke = "#dc2626" if (c, r) in obs else "#e2e8f0"
                grid_svg += f'<rect x="{x}" y="{y}" width="{cell}" height="{cell}" fill="{fill}" stroke="{stroke}" stroke-width="1"/>\n'
                if (c, r) in obs:
                    grid_svg += f'<line x1="{x}" y1="{y}" x2="{x+cell}" y2="{y+cell}" stroke="#fca5a5" stroke-width="1"/>\n'

        color = "#059669" if is_theta else "#dc2626"
        grid_svg += f'<path d="M' + ' L'.join(f'{x},{y}' for x,y in pts) + f'" stroke="{color}" stroke-width="3.5" fill="none" stroke-linecap="round" stroke-linejoin="round"/>\n'
        for x, y in pts:
            grid_svg += f'<circle cx="{x}" cy="{y}" r="3.5" fill="{color}" stroke="#ffffff" stroke-width="1.5"/>\n'

        sx, sy = ox + start_cell[0]*cell + cell/2, oy + start_cell[1]*cell + cell/2
        gx, gy = ox + goal_cell[0]*cell + cell/2, oy + goal_cell[1]*cell + cell/2
        grid_svg += f'<circle cx="{sx}" cy="{sy}" r="6" fill="#059669" stroke="#ffffff" stroke-width="2"/>\n'
        grid_svg += f'<text x="{sx-14}" y="{sy+4}" font-family="Inter" font-size="11" font-weight="700" fill="#059669">S</text>\n'
        grid_svg += f'<circle cx="{gx}" cy="{gy}" r="6" fill="#dc2626" stroke="#ffffff" stroke-width="2"/>\n'
        grid_svg += f'<text x="{gx+8}" y="{gy+4}" font-family="Inter" font-size="11" font-weight="700" fill="#dc2626">G</text>\n'
        return grid_svg

    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 360" width="100%" height="100%">
  <rect width="100%" height="100%" rx="10" fill="#ffffff" stroke="#e2e8f0" stroke-width="1.5"/>

  <!-- LEFT: STANDARD A* -->
  <g transform="translate(20, 20)">
    <rect width="345" height="320" rx="8" fill="#f8fafc" stroke="#e2e8f0" stroke-width="1"/>
    <text x="16" y="24" font-family="Inter, sans-serif" font-size="14" font-weight="700" fill="#0f172a">1. Классический 8-связный A*</text>
    <text x="16" y="39" font-family="Inter, sans-serif" font-size="11" fill="#64748b">Траектория жестко привязана к сетке (углы 0°, 45°, 90°)</text>

    {render_grid(astar_pts, False)}

    <rect x="14" y="270" width="317" height="38" rx="5" fill="#ffffff" stroke="#cbd5e1" stroke-width="1"/>
    <text x="24" y="287" font-family="Inter, sans-serif" font-size="11.5" font-weight="700" fill="#dc2626">Длина пути: L = {astar_dist:.2f} клеток</text>
    <text x="24" y="301" font-family="Inter, sans-serif" font-size="10" fill="#64748b">Избыточные изломы и искусственные повороты на ребрах сетки</text>
  </g>

  <!-- RIGHT: THETA* ANY-ANGLE -->
  <g transform="translate(395, 20)">
    <rect width="345" height="320" rx="8" fill="#f8fafc" stroke="#e2e8f0" stroke-width="1"/>
    <text x="16" y="24" font-family="Inter, sans-serif" font-size="14" font-weight="700" fill="#0f172a">2. Theta* (Any-Angle Path Planning)</text>
    <text x="16" y="39" font-family="Inter, sans-serif" font-size="11" fill="#64748b">LineOfSight(parent(s), s') сглаживает путь напрямую</text>

    {render_grid(theta_pts, True)}

    <!-- Line of sight ray indicator -->
    <line x1="{ox + 2*cell + cell/2}" y1="{oy + 4*cell + cell/2}" x2="{ox + 6*cell + cell/2}" y2="{oy + 1*cell + cell/2}" stroke="#0284c7" stroke-width="1.5" stroke-dasharray="3,3"/>
    <text x="155" y="145" font-family="JetBrains Mono, monospace" font-size="9" fill="#0284c7">LineOfSight() = True</text>

    <rect x="14" y="270" width="317" height="38" rx="5" fill="#ffffff" stroke="#cbd5e1" stroke-width="1"/>
    <text x="24" y="287" font-family="Inter, sans-serif" font-size="11.5" font-weight="700" fill="#059669">Длина пути: L = {theta_dist:.2f} клеток (-{((astar_dist-theta_dist)/astar_dist)*100:.1f}%)</text>
    <text x="24" y="301" font-family="Inter, sans-serif" font-size="10" fill="#64748b">Устраняет дискретный артефакт сетки без пост-сглаживания</text>
  </g>
</svg>'''

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(svg)
    print(f"Generated: {filepath}")

# -------------------------------------------------------------------------
# Diagram 3: Lecture 01 - Minkowski Sum & C-Space
# -------------------------------------------------------------------------
def generate_minkowski_cspace():
    filepath = os.path.join(OUTPUT_DIR, 'lecture-01', 'minkowski_cspace.svg')
    ensure_dir(filepath)

    O = [(60, 60), (160, 50), (195, 125), (120, 160), (45, 115)]
    neg_A = [(20, 15), (-25, 0), (20, -15)]

    c_obs_points = []
    for ox, oy in O:
        for ax, ay in neg_A:
            c_obs_points.append((ox + ax, oy + ay))

    C_obs = convex_hull(c_obs_points)

    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 360" width="100%" height="100%">
  <rect width="100%" height="100%" rx="10" fill="#ffffff" stroke="#e2e8f0" stroke-width="1.5"/>

  <!-- LEFT: WORKSPACE W -->
  <g transform="translate(20, 20)">
    <rect width="345" height="320" rx="8" fill="#f8fafc" stroke="#e2e8f0" stroke-width="1"/>
    <text x="16" y="24" font-family="Inter, sans-serif" font-size="14" font-weight="700" fill="#0f172a">1. Рабочее пространство W</text>
    <text x="16" y="39" font-family="Inter, sans-serif" font-size="11" fill="#64748b">Препятствие O и физический робот с габаритами A(q)</text>

    <!-- Obstacle O -->
    <polygon points="{' '.join(f'{x},{y}' for x,y in O)}" fill="#fee2e2" stroke="#ef4444" stroke-width="2"/>
    <text x="95" y="105" font-family="Inter, sans-serif" font-size="12" font-weight="700" fill="#b91c1c">Препятствие O</text>

    <!-- Robot at position q = (180, 200) -->
    <g transform="translate(190, 195) rotate(20)">
      <polygon points="-20,-15 25,0 -20,15" fill="#dbeafe" stroke="#2563eb" stroke-width="2"/>
      <circle cx="0" cy="0" r="3.5" fill="#2563eb"/>
      <line x1="0" y1="0" x2="25" y2="0" stroke="#1d4ed8" stroke-width="2"/>
    </g>
    <circle cx="190" cy="195" r="4" fill="#2563eb"/>
    <text x="145" y="228" font-family="Inter, sans-serif" font-size="11.5" font-weight="600" fill="#1d4ed8">Робот A(q) (размер &gt; 0)</text>
    <text x="145" y="243" font-family="JetBrains Mono, monospace" font-size="10" fill="#64748b">q = (x, y, θ)</text>

    <rect x="14" y="260" width="317" height="48" rx="5" fill="#ffffff" stroke="#cbd5e1" stroke-width="1"/>
    <text x="24" y="278" font-family="Inter, sans-serif" font-size="11" fill="#334155">Коллизия возникает, когда пересекаются тела:</text>
    <text x="24" y="295" font-family="JetBrains Mono, monospace" font-size="11" font-weight="700" fill="#b91c1c">Collision ⟺ A(q) ∩ O ≠ ∅</text>
  </g>

  <!-- CENTER FORMULA OPERATOR -->
  <g transform="translate(345, 155)">
    <circle cx="25" cy="25" r="20" fill="#0284c7" fill-opacity="0.1" stroke="#0284c7" stroke-width="1.5"/>
    <text x="18" y="31" font-family="Inter, sans-serif" font-size="16" font-weight="700" fill="#0284c7">⊕</text>
  </g>

  <!-- RIGHT: CONFIGURATION SPACE C-SPACE -->
  <g transform="translate(395, 20)">
    <rect width="345" height="320" rx="8" fill="#f8fafc" stroke="#e2e8f0" stroke-width="1"/>
    <text x="16" y="24" font-family="Inter, sans-serif" font-size="14" font-weight="700" fill="#0f172a">2. Конфигурационное пространство C-space</text>
    <text x="16" y="39" font-family="Inter, sans-serif" font-size="11" fill="#64748b">Срез при фиксированном угле θ: робот сжат в точку q!</text>

    <!-- Computed Minkowski Sum C_obs -->
    <polygon points="{' '.join(f'{x},{y}' for x,y in C_obs)}" fill="#fecaca" stroke="#dc2626" stroke-width="2.2" stroke-dasharray="4,2"/>
    <polygon points="{' '.join(f'{x},{y}' for x,y in O)}" fill="#fee2e2" stroke="#f87171" stroke-width="1" opacity="0.6"/>

    <text x="80" y="105" font-family="Inter, sans-serif" font-size="12" font-weight="700" fill="#991b1b">C_obs = O ⊕ (-A(0))</text>
    <text x="80" y="122" font-family="Inter, sans-serif" font-size="10" fill="#b91c1c">(Раздутая запретная зона)</text>

    <!-- Point robot q and clearance path -->
    <path d="M25,210 Q110,215 190,195 T260,80" stroke="#059669" stroke-width="2.5" fill="none" stroke-dasharray="3,3"/>
    <circle cx="190" cy="195" r="5" fill="#059669" stroke="#ffffff" stroke-width="2"/>
    <text x="160" y="222" font-family="Inter, sans-serif" font-size="11.5" font-weight="700" fill="#047857">Точка q ∈ C_free</text>

    <rect x="14" y="260" width="317" height="48" rx="5" fill="#ffffff" stroke="#cbd5e1" stroke-width="1"/>
    <text x="24" y="278" font-family="Inter, sans-serif" font-size="11" fill="#334155">Планирование пути сложного робота сводится к</text>
    <text x="24" y="295" font-family="JetBrains Mono, monospace" font-size="11" font-weight="700" fill="#059669">поиску траектории материальной точки q в C_free</text>
  </g>
</svg>'''

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(svg)
    print(f"Generated: {filepath}")

# -------------------------------------------------------------------------
# Diagram 4: Lecture 01 - Euclidean Signed Distance Field (ESDF)
# -------------------------------------------------------------------------
def generate_sdf_gradient():
    filepath = os.path.join(OUTPUT_DIR, 'lecture-01', 'sdf_gradient.svg')
    ensure_dir(filepath)

    cx, cy = 150, 140
    rx, ry = 50, 35

    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 360" width="100%" height="100%">
  <rect width="100%" height="100%" rx="10" fill="#ffffff" stroke="#e2e8f0" stroke-width="1.5"/>

  <!-- LEFT: ESDF ISOLINES -->
  <g transform="translate(20, 20)">
    <rect width="345" height="320" rx="8" fill="#f8fafc" stroke="#e2e8f0" stroke-width="1"/>
    <text x="16" y="24" font-family="Inter, sans-serif" font-size="14" font-weight="700" fill="#0f172a">1. Евклидово поле расстояний (ESDF)</text>
    <text x="16" y="39" font-family="Inter, sans-serif" font-size="11" fill="#64748b">Изолинии расстояния d(x) = min_{{p ∈ ∂O}} ||x - p||</text>

    <!-- Isolines d = 80, 55, 30 -->
    <ellipse cx="{cx}" cy="{cy}" rx="{rx + 80}" ry="{ry + 65}" fill="#f0f9ff" stroke="#bae6fd" stroke-width="1.2" stroke-dasharray="3,3"/>
    <ellipse cx="{cx}" cy="{cy}" rx="{rx + 55}" ry="{ry + 45}" fill="#e0f2fe" stroke="#7dd3fc" stroke-width="1.4" stroke-dasharray="3,3"/>
    <ellipse cx="{cx}" cy="{cy}" rx="{rx + 30}" ry="{ry + 25}" fill="#bae6fd" stroke="#38bdf8" stroke-width="1.6"/>

    <!-- Obstacle (d <= 0) -->
    <ellipse cx="{cx}" cy="{cy}" rx="{rx}" ry="{ry}" fill="#ef4444" stroke="#b91c1c" stroke-width="2"/>
    <text x="{cx-28}" y="{cy+4}" font-family="Inter, sans-serif" font-size="11" font-weight="700" fill="#ffffff">Препятствие</text>

    <!-- Labels on isolines -->
    <text x="{cx+rx+10}" y="{cy-18}" font-family="JetBrains Mono, monospace" font-size="10" font-weight="600" fill="#0369a1">d = +0.5 м</text>
    <text x="{cx+rx+35}" y="{cy-38}" font-family="JetBrains Mono, monospace" font-size="10" font-weight="600" fill="#0284c7">d = +1.0 м</text>
    <text x="{cx+rx+60}" y="{cy-58}" font-family="JetBrains Mono, monospace" font-size="10" font-weight="600" fill="#0369a1">d = +1.5 м</text>

    <rect x="14" y="250" width="317" height="58" rx="5" fill="#ffffff" stroke="#cbd5e1" stroke-width="1"/>
    <text x="24" y="270" font-family="Inter, sans-serif" font-size="11" font-weight="700" fill="#0284c7">Свойства поля расстояний:</text>
    <text x="24" y="286" font-family="JetBrains Mono, monospace" font-size="10" fill="#334155">d(x) &gt; 0 в свободном пространстве, d(x) = 0 на границе</text>
    <text x="24" y="299" font-family="Inter, sans-serif" font-size="10" fill="#64748b">Вычисляется на GPU через nvblox / VDB-EDT в реалтайме</text>
  </g>

  <!-- RIGHT: GRADIENT FIELD -->
  <g transform="translate(395, 20)">
    <rect width="345" height="320" rx="8" fill="#f8fafc" stroke="#e2e8f0" stroke-width="1"/>
    <text x="16" y="24" font-family="Inter, sans-serif" font-size="14" font-weight="700" fill="#0f172a">2. Градиент ∇ESDF и силы отталкивания</text>
    <text x="16" y="39" font-family="Inter, sans-serif" font-size="11" fill="#64748b">Векторы ∇d(x) перпендикулярны поверхности (нормали n)</text>

    <ellipse cx="{cx}" cy="{cy}" rx="{rx}" ry="{ry}" fill="#fee2e2" stroke="#ef4444" stroke-width="2"/>
    <text x="{cx-28}" y="{cy+4}" font-family="Inter, sans-serif" font-size="11" font-weight="700" fill="#b91c1c">Препятствие</text>
'''
    angles = [i * (2 * math.pi / 12) for i in range(12)]
    for a in angles:
        px = cx + rx * math.cos(a)
        py = cy + ry * math.sin(a)
        nx = math.cos(a) / rx
        ny = math.sin(a) / ry
        nlen = math.hypot(nx, ny)
        nx /= nlen
        ny /= nlen
        vec_len = 32
        x2 = px + nx * vec_len
        y2 = py + ny * vec_len
        svg += f'''    <line x1="{px:.1f}" y1="{py:.1f}" x2="{x2:.1f}" y2="{y2:.1f}" stroke="#0284c7" stroke-width="2"/>
    <circle cx="{x2:.1f}" cy="{y2:.1f}" r="2" fill="#0284c7"/>
'''

    svg += f'''
    <rect x="14" y="250" width="317" height="58" rx="5" fill="#ffffff" stroke="#cbd5e1" stroke-width="1"/>
    <text x="24" y="270" font-family="Inter, sans-serif" font-size="11" font-weight="700" fill="#059669">Непрерывный градиент для оптимизаторов:</text>
    <text x="24" y="286" font-family="JetBrains Mono, monospace" font-size="10" fill="#0f172a">F_rep = -∇ESDF(x) / ||∇ESDF||  (Единичный вектор)</text>
    <text x="24" y="299" font-family="Inter, sans-serif" font-size="10" fill="#64748b">Обеспечивает C¹-гладкость функционала в CHOMP, TrajOpt и MPC</text>
  </g>
</svg>'''

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(svg)
    print(f"Generated: {filepath}")

# -------------------------------------------------------------------------
# Diagram 5: Lecture 03 - RRT* Rewiring
# -------------------------------------------------------------------------
def generate_rrt_star_rewire():
    filepath = os.path.join(OUTPUT_DIR, 'lecture-03', 'rrt_star_rewire.svg')
    ensure_dir(filepath)

    q_new = (220, 160)
    r_rewire = 90

    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 360" width="100%" height="100%">
  <rect width="100%" height="100%" rx="10" fill="#ffffff" stroke="#e2e8f0" stroke-width="1.5"/>

  <!-- Title & Legend -->
  <g transform="translate(30, 24)">
    <text x="0" y="0" font-family="Inter, sans-serif" font-size="15" font-weight="700" fill="#0f172a">Алгоритм переподключения RRT* (Rewiring Step)</text>
    <text x="0" y="18" font-family="Inter, sans-serif" font-size="11.5" fill="#64748b">Окрестность радиуса r_RRT* вокруг q_new проверяется на оптимизацию стоимости пути c(v)</text>
  </g>

  <!-- Rewiring Circle Area -->
  <circle cx="{q_new[0]}" cy="{q_new[1]}" r="{r_rewire}" fill="#f0fdf4" stroke="#86efac" stroke-width="1.5" stroke-dasharray="4,3"/>
  <line x1="{q_new[0]}" y1="{q_new[1]}" x2="{q_new[0] + r_rewire * 0.7}" y2="{q_new[1] - r_rewire * 0.7}" stroke="#10b981" stroke-width="1.2"/>
  <text x="{q_new[0] + 30}" y="{q_new[1] - 35}" font-family="JetBrains Mono, monospace" font-size="10" fill="#059669">r_RRT*</text>

  <!-- Existing Tree Edges -->
  <g stroke="#94a3b8" stroke-width="2">
    <line x1="60" y1="160" x2="120" y2="110"/>
    <line x1="60" y1="160" x2="130" y2="210"/>
    <line x1="120" y1="110" x2="155" y2="140"/>
    <line x1="130" y1="210" x2="280" y2="215"/>
  </g>

  <!-- OLD SUBOPTIMAL EDGE (TO BE DROPPED) -->
  <line x1="120" y1="110" x2="285" y2="130" stroke="#ef4444" stroke-width="2.5" stroke-dasharray="5,3"/>
  <text x="195" y="112" font-family="Inter, sans-serif" font-size="11" font-weight="700" fill="#dc2626">✗ Старое ребро (c = 22.8)</text>

  <!-- NEW OPTIMAL EDGE TO q_new -->
  <line x1="155" y1="140" x2="{q_new[0]}" y2="{q_new[1]}" stroke="#0284c7" stroke-width="3"/>
  <text x="160" y="172" font-family="JetBrains Mono, monospace" font-size="9.5" fill="#0369a1">c(q_new) = 13.8</text>

  <!-- NEW REWIRED EDGE (q_new -> v) -->
  <line x1="{q_new[0]}" y1="{q_new[1]}" x2="285" y2="130" stroke="#059669" stroke-width="3.5" stroke-linecap="round"/>
  <text x="235" y="140" font-family="Inter, sans-serif" font-size="11" font-weight="700" fill="#059669">✓ Новое ребро (c = 17.5)</text>

  <!-- Nodes -->
  <circle cx="60" cy="160" r="6" fill="#0f172a"/>
  <text x="40" y="180" font-family="JetBrains Mono" font-size="10" fill="#475569">q_start</text>

  <circle cx="120" cy="110" r="5" fill="#64748b"/>
  <circle cx="130" cy="210" r="5" fill="#64748b"/>
  <circle cx="155" cy="140" r="5" fill="#0284c7"/>
  <circle cx="280" cy="215" r="5" fill="#64748b"/>

  <!-- Target Node v -->
  <circle cx="285" cy="130" r="6.5" fill="#059669" stroke="#ffffff" stroke-width="2"/>
  <text x="296" y="134" font-family="Inter" font-size="12" font-weight="700" fill="#059669">Вершина v</text>

  <!-- New Sample q_new -->
  <circle cx="{q_new[0]}" cy="{q_new[1]}" r="7" fill="#0284c7" stroke="#ffffff" stroke-width="2"/>
  <text x="{q_new[0]-14}" y="{q_new[1]-12}" font-family="Inter" font-size="12" font-weight="700" fill="#0284c7">q_new</text>

  <!-- Mathematical explanation card -->
  <g transform="translate(420, 80)">
    <rect width="310" height="230" rx="8" fill="#f8fafc" stroke="#e2e8f0" stroke-width="1"/>
    <text x="16" y="24" font-family="Inter, sans-serif" font-size="13" font-weight="700" fill="#0f172a">Условие переподключения (Rewire):</text>
    <rect x="14" y="36" width="282" height="42" rx="4" fill="#eff6ff" stroke="#bfdbfe" stroke-width="1"/>
    <text x="22" y="61" font-family="JetBrains Mono, monospace" font-size="11" font-weight="700" fill="#1e40af">cost(q_new) + ||q_new - v|| &lt; cost(v)</text>

    <text x="16" y="105" font-family="Inter, sans-serif" font-size="11.5" fill="#334155">1. <tspan font-weight="700">Выбор родителя:</tspan> q_new подключается к узлу окрестности с наименьшей суммарной стоимостью от старта.</text>
    <text x="16" y="145" font-family="Inter, sans-serif" font-size="11.5" fill="#334155">2. <tspan font-weight="700">Переподключение:</tspan> все соседние вершины v перенаправляют родителя на q_new, если путь через него короче.</text>
    <text x="16" y="185" font-family="Inter, sans-serif" font-size="11.5" fill="#334155">3. <tspan font-weight="700">Результат:</tspan> устраняются зигзаги, дерево асимптотически сходится к строго оптимальному пути.</text>

    <rect x="14" y="200" width="282" height="22" rx="3" fill="#fef2f2"/>
    <text x="20" y="215" font-family="JetBrains Mono, monospace" font-size="9.5" fill="#991b1b">P(lim_{{n→∞}} Cost(RRT*) = Cost*) = 1</text>
  </g>
</svg>'''

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(svg)
    print(f"Generated: {filepath}")

# -------------------------------------------------------------------------
# Diagram 6: Lecture 03 - Informed RRT* Ellipsoid
# -------------------------------------------------------------------------
def generate_informed_rrt_ellipse():
    filepath = os.path.join(OUTPUT_DIR, 'lecture-03', 'informed_rrt_ellipse.svg')
    ensure_dir(filepath)

    x_s = (120, 160)
    x_g = (460, 160)
    c_min = dist(x_s, x_g)
    c_best = 400
    a = c_best / 2
    b = math.sqrt(c_best**2 - c_min**2) / 2
    cx, cy = (x_s[0] + x_g[0]) / 2, (x_s[1] + x_g[1]) / 2

    random.seed(42)
    samples_in = []
    samples_out = []
    for _ in range(65):
        rx = random.uniform(cx - a*1.25, cx + a*1.25)
        ry = random.uniform(cy - b*1.35, cy + b*1.35)
        val = ((rx - cx)/a)**2 + ((ry - cy)/b)**2
        if val <= 1.0:
            samples_in.append((rx, ry))
        else:
            samples_out.append((rx, ry))

    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 360" width="100%" height="100%">
  <rect width="100%" height="100%" rx="10" fill="#ffffff" stroke="#e2e8f0" stroke-width="1.5"/>

  <g transform="translate(30, 24)">
    <text x="0" y="0" font-family="Inter, sans-serif" font-size="15" font-weight="700" fill="#0f172a">Informed RRT*: Сжатие выборки в эллипсоид C_best</text>
    <text x="0" y="18" font-family="Inter, sans-serif" font-size="11.5" fill="#64748b">После нахождения первого пути сэмплирование сужается до эллипсоида равной стоимости</text>
  </g>

  <rect x="30" y="60" width="520" height="240" fill="#f8fafc" stroke="#cbd5e1" stroke-width="1.2" stroke-dasharray="4,4"/>
  <text x="40" y="78" font-family="Inter, sans-serif" font-size="11" fill="#94a3b8">Исходное пространство поиска X</text>

  <g fill="#cbd5e1">
'''
    for x, y in samples_out:
        svg += f'    <circle cx="{x:.1f}" cy="{y:.1f}" r="2.5"/>\n'

    svg += f'''  </g>

  <ellipse cx="{cx}" cy="{cy}" rx="{a}" ry="{b}" fill="#ecfdf5" stroke="#059669" stroke-width="2.5"/>

  <g fill="#059669">
'''
    for x, y in samples_in:
        svg += f'    <circle cx="{x:.1f}" cy="{y:.1f}" r="3"/>\n'

    svg += f'''  </g>

  <line x1="{cx - a}" y1="{cy}" x2="{cx + a}" y2="{cy}" stroke="#059669" stroke-width="1" stroke-dasharray="3,3"/>
  <line x1="{cx}" y1="{cy - b}" x2="{cx}" y2="{cy + b}" stroke="#059669" stroke-width="1" stroke-dasharray="3,3"/>

  <path d="M{x_s[0]},{x_s[1]} L190,110 L280,210 L380,120 L{x_g[0]},{x_g[1]}" stroke="#d97706" stroke-width="2.2" fill="none" stroke-linecap="round"/>

  <circle cx="{x_s[0]}" cy="{x_s[1]}" r="6.5" fill="#0284c7" stroke="#ffffff" stroke-width="2"/>
  <text x="{x_s[0]-14}" y="{x_s[1]+18}" font-family="Inter" font-size="11" font-weight="700" fill="#0284c7">x_start (Фокус 1)</text>

  <circle cx="{x_g[0]}" cy="{x_g[1]}" r="6.5" fill="#dc2626" stroke="#ffffff" stroke-width="2"/>
  <text x="{x_g[0]-14}" y="{x_g[1]+18}" font-family="Inter" font-size="11" font-weight="700" fill="#dc2626">x_goal (Фокус 2)</text>

  <g transform="translate(565, 60)">
    <rect width="165" height="240" rx="8" fill="#f8fafc" stroke="#e2e8f0" stroke-width="1"/>
    <text x="14" y="24" font-family="Inter, sans-serif" font-size="12" font-weight="700" fill="#0f172a">Параметры эллипса:</text>
    
    <text x="14" y="50" font-family="JetBrains Mono" font-size="10" fill="#0f172a">• c_min = ||x_g - x_s||</text>
    <text x="14" y="68" font-family="JetBrains Mono" font-size="10" fill="#d97706">• c_best = длина пути</text>
    <text x="14" y="86" font-family="JetBrains Mono" font-size="10" fill="#059669">• Большая полуось a:</text>
    <text x="24" y="102" font-family="JetBrains Mono" font-size="10.5" font-weight="700" fill="#059669">a = c_best / 2</text>
    
    <text x="14" y="124" font-family="JetBrains Mono" font-size="10" fill="#059669">• Малая полуось b:</text>
    <text x="24" y="140" font-family="JetBrains Mono" font-size="10.5" font-weight="700" fill="#059669">b = √(c_best² - c_min²)/2</text>

    <rect x="10" y="165" width="145" height="60" rx="4" fill="#ecfdf5" stroke="#a7f3d0" stroke-width="1"/>
    <text x="16" y="184" font-family="Inter, sans-serif" font-size="10.5" font-weight="700" fill="#065f46">Эффект сжатия:</text>
    <text x="16" y="200" font-family="Inter, sans-serif" font-size="9.5" fill="#047857">Отсекает до 90% нерелевантного пространства!</text>
  </g>
</svg>'''

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(svg)
    print(f"Generated: {filepath}")

# -------------------------------------------------------------------------
# Diagram 7: Lecture 04 - APF U-Trap vs Harmonic Field
# -------------------------------------------------------------------------
def generate_apf_u_trap():
    filepath = os.path.join(OUTPUT_DIR, 'lecture-04', 'apf_u_trap.svg')
    ensure_dir(filepath)

    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 360" width="100%" height="100%">
  <rect width="100%" height="100%" rx="10" fill="#ffffff" stroke="#e2e8f0" stroke-width="1.5"/>

  <g transform="translate(20, 20)">
    <rect width="345" height="320" rx="8" fill="#f8fafc" stroke="#e2e8f0" stroke-width="1"/>
    <text x="16" y="24" font-family="Inter, sans-serif" font-size="14" font-weight="700" fill="#0f172a">1. Классический метод Хатиба (APF)</text>
    <text x="16" y="39" font-family="Inter, sans-serif" font-size="11" fill="#dc2626">Патология: U-ловушка и локальный минимум ∇U = 0</text>

    <path d="M120,70 V190 H220 V70" stroke="#ef4444" stroke-width="14" fill="none" stroke-linejoin="round" stroke-linecap="round"/>
    <text x="145" y="145" font-family="Inter, sans-serif" font-size="11.5" font-weight="700" fill="#991b1b">U-ловушка</text>

    <circle cx="170" cy="40" r="7" fill="#0284c7" stroke="#ffffff" stroke-width="2"/>
    <text x="185" y="44" font-family="Inter" font-size="11" font-weight="700" fill="#0284c7">Цель (G)</text>

    <path d="M170,270 L170,165" stroke="#dc2626" stroke-width="3" stroke-linecap="round"/>
    <circle cx="170" cy="270" r="5" fill="#059669"/>
    <text x="150" y="290" font-family="Inter" font-size="10.5" fill="#059669">Старт (S)</text>

    <circle cx="170" cy="165" r="7" fill="#dc2626" stroke="#ffffff" stroke-width="2"/>
    <circle cx="170" cy="165" r="14" fill="none" stroke="#dc2626" stroke-width="1.5" stroke-dasharray="3,3"/>

    <line x1="170" y1="165" x2="170" y2="135" stroke="#0284c7" stroke-width="2"/>
    <text x="175" y="145" font-family="JetBrains Mono" font-size="10" font-weight="700" fill="#0284c7">F_att ↑</text>
    <line x1="170" y1="165" x2="170" y2="195" stroke="#ef4444" stroke-width="2"/>
    <text x="175" y="190" font-family="JetBrains Mono" font-size="10" font-weight="700" fill="#ef4444">F_rep ↓</text>

    <rect x="14" y="240" width="317" height="68" rx="5" fill="#fef2f2" stroke="#fca5a5" stroke-width="1"/>
    <text x="24" y="260" font-family="Inter, sans-serif" font-size="11.5" font-weight="700" fill="#991b1b">Суммарная сила F_net = F_att + F_rep = 0</text>
    <text x="24" y="278" font-family="Inter, sans-serif" font-size="10.5" fill="#7f1d1d">Робот парализован: притяжение к цели строго равно отталкиванию от дна тупика!</text>
  </g>

  <g transform="translate(395, 20)">
    <rect width="345" height="320" rx="8" fill="#f8fafc" stroke="#e2e8f0" stroke-width="1"/>
    <text x="16" y="24" font-family="Inter, sans-serif" font-size="14" font-weight="700" fill="#0f172a">2. Гармоническое поле (Harmonic Field)</text>
    <text x="16" y="39" font-family="Inter, sans-serif" font-size="11" fill="#059669">Уравнение Лапласа ∇²φ = 0 (Принцип максимума)</text>

    <path d="M120,70 V190 H220 V70" stroke="#94a3b8" stroke-width="14" fill="none" stroke-linejoin="round" stroke-linecap="round"/>
    <text x="145" y="145" font-family="Inter, sans-serif" font-size="11" font-weight="600" fill="#475569">Преграда</text>

    <circle cx="170" cy="40" r="7" fill="#0284c7" stroke="#ffffff" stroke-width="2"/>
    <text x="185" y="44" font-family="Inter" font-size="11" font-weight="700" fill="#0284c7">φ = 0 (Goal)</text>

    <path d="M170,270 Q170,210 95,200 Q75,120 120,55 Q145,40 170,40" stroke="#059669" stroke-width="3" fill="none" stroke-linecap="round"/>
    <path d="M170,270 Q170,210 245,200 Q265,120 220,55 Q195,40 170,40" stroke="#059669" stroke-width="3" fill="none" stroke-linecap="round"/>

    <circle cx="170" cy="270" r="5" fill="#059669"/>
    <text x="150" y="290" font-family="Inter" font-size="10.5" fill="#059669">Старт (S)</text>

    <rect x="14" y="240" width="317" height="68" rx="5" fill="#ecfdf5" stroke="#a7f3d0" stroke-width="1"/>
    <text x="24" y="260" font-family="Inter, sans-serif" font-size="11.5" font-weight="700" fill="#065f46">Принцип максимума гармонических функций:</text>
    <text x="24" y="278" font-family="Inter, sans-serif" font-size="10.5" fill="#047857">Экстремумы достигаются ТОЛЬКО на границах! Внутри свободной зоны локальные минимумы невозможны.</text>
  </g>
</svg>'''

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(svg)
    print(f"Generated: {filepath}")

# -------------------------------------------------------------------------
# Diagram 8: Lecture 04 - DWA Dynamic Window Approach
# -------------------------------------------------------------------------
def generate_dwa_space():
    filepath = os.path.join(OUTPUT_DIR, 'lecture-04', 'dwa_space.svg')
    ensure_dir(filepath)

    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 360" width="100%" height="100%">
  <rect width="100%" height="100%" rx="10" fill="#ffffff" stroke="#e2e8f0" stroke-width="1.5"/>

  <g transform="translate(20, 20)">
    <rect width="345" height="320" rx="8" fill="#f8fafc" stroke="#e2e8f0" stroke-width="1"/>
    <text x="16" y="24" font-family="Inter, sans-serif" font-size="14" font-weight="700" fill="#0f172a">1. Пространство скоростей (v, ω)</text>
    <text x="16" y="39" font-family="Inter, sans-serif" font-size="11" fill="#64748b">Пересечение ограничений: Vr = Vs ∩ Vd ∩ Va</text>

    <line x1="40" y1="230" x2="310" y2="230" stroke="#94a3b8" stroke-width="1.5"/>
    <line x1="175" y1="245" x2="175" y2="55" stroke="#94a3b8" stroke-width="1.5"/>
    <text x="315" y="234" font-family="JetBrains Mono" font-size="11" font-weight="700" fill="#475569">ω</text>
    <text x="170" y="48" font-family="JetBrains Mono" font-size="11" font-weight="700" fill="#475569">v</text>

    <rect x="75" y="70" width="200" height="160" fill="none" stroke="#cbd5e1" stroke-width="1.5" stroke-dasharray="3,3"/>
    <text x="80" y="85" font-family="Inter" font-size="10" fill="#94a3b8">Vs (Моторы)</text>

    <rect x="130" y="110" width="105" height="85" fill="#dbeafe" fill-opacity="0.6" stroke="#3b82f6" stroke-width="1.5"/>
    <text x="136" y="125" font-family="Inter" font-size="10" font-weight="600" fill="#1e40af">Vd (Ускорение)</text>

    <path d="M110,210 Q175,130 260,210 Z" fill="#fee2e2" fill-opacity="0.5" stroke="#ef4444" stroke-width="1.5"/>
    <text x="180" y="195" font-family="Inter" font-size="9.5" fill="#b91c1c">Va (Препятствия)</text>

    <circle cx="170" cy="165" r="4.5" fill="#0f172a"/>
    <text x="180" y="165" font-family="JetBrains Mono" font-size="9.5" fill="#0f172a">(v₀, ω₀)</text>

    <circle cx="205" cy="135" r="6" fill="#059669" stroke="#ffffff" stroke-width="1.5"/>
    <text x="215" y="132" font-family="Inter" font-size="11" font-weight="700" fill="#059669">(v*, ω*)</text>

    <rect x="14" y="255" width="317" height="52" rx="5" fill="#ffffff" stroke="#cbd5e1" stroke-width="1"/>
    <text x="22" y="274" font-family="JetBrains Mono" font-size="10" font-weight="700" fill="#0284c7">G(v, ω) = α·heading + β·dist + γ·vel</text>
    <text x="22" y="292" font-family="Inter" font-size="10" fill="#64748b">Максимизация критерия целевой функции в окне Vr</text>
  </g>

  <g transform="translate(395, 20)">
    <rect width="345" height="320" rx="8" fill="#f8fafc" stroke="#e2e8f0" stroke-width="1"/>
    <text x="16" y="24" font-family="Inter, sans-serif" font-size="14" font-weight="700" fill="#0f172a">2. Траектории в пространстве W</text>
    <text x="16" y="39" font-family="Inter, sans-serif" font-size="11" fill="#64748b">Каждой паре (v, ω) соответствует круговая дуга радиуса R = v/ω</text>

    <rect x="160" y="260" width="26" height="36" rx="3" fill="#0f172a"/>
    <circle cx="173" cy="278" r="3" fill="#38bdf8"/>

    <circle cx="130" cy="140" r="28" fill="#fee2e2" stroke="#ef4444" stroke-width="2"/>
    <text x="115" y="144" font-family="Inter" font-size="10.5" font-weight="700" fill="#b91c1c">Преграда</text>

    <circle cx="240" cy="70" r="7" fill="#0284c7" stroke="#ffffff" stroke-width="2"/>
    <text x="252" y="74" font-family="Inter" font-size="11" font-weight="700" fill="#0284c7">Цель</text>

    <path d="M173,260 Q170,180 135,140" stroke="#ef4444" stroke-width="1.8" fill="none" stroke-dasharray="3,3"/>
    <path d="M173,260 Q173,190 173,80" stroke="#94a3b8" stroke-width="1.8" fill="none"/>
    <path d="M173,260 Q180,180 280,150" stroke="#94a3b8" stroke-width="1.8" fill="none"/>

    <path d="M173,260 Q180,160 240,75" stroke="#059669" stroke-width="3.5" fill="none" stroke-linecap="round"/>
    <text x="210" y="175" font-family="Inter" font-size="11" font-weight="700" fill="#059669">Дуга (v*, ω*)</text>

    <rect x="14" y="255" width="317" height="52" rx="5" fill="#ffffff" stroke="#cbd5e1" stroke-width="1"/>
    <text x="22" y="274" font-family="Inter" font-size="11" font-weight="700" fill="#059669">Выбирается дуга с лучшим клиренсом и скоростью</text>
    <text x="22" y="292" font-family="Inter" font-size="10" fill="#64748b">Контроллер Nav2 DWA работает с частотой 20–50 Гц</text>
  </g>
</svg>'''

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(svg)
    print(f"Generated: {filepath}")

# -------------------------------------------------------------------------
# Diagram 9: Lecture 04 - TEB Timed Elastic Band
# -------------------------------------------------------------------------
def generate_teb_elastic_band():
    filepath = os.path.join(OUTPUT_DIR, 'lecture-04', 'teb_elastic_band.svg')
    ensure_dir(filepath)

    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 360" width="100%" height="100%">
  <rect width="100%" height="100%" rx="10" fill="#ffffff" stroke="#e2e8f0" stroke-width="1.5"/>

  <g transform="translate(30, 24)">
    <text x="0" y="0" font-family="Inter, sans-serif" font-size="15" font-weight="700" fill="#0f172a">Timed Elastic Band (TEB): Оптимизация ленты состояний и гомотопии</text>
    <text x="0" y="18" font-family="Inter, sans-serif" font-size="11.5" fill="#64748b">Траектория B = {{s_i, Δt_i}} деформируется как упругая лента под действием виртуальных сил</text>
  </g>

  <circle cx="360" cy="170" r="42" fill="#fee2e2" stroke="#ef4444" stroke-width="2.2"/>
  <text x="328" y="174" font-family="Inter, sans-serif" font-size="12" font-weight="700" fill="#b91c1c">Препятствие</text>

  <path d="M90,240 Q180,85 360,85 Q520,85 640,240" stroke="#059669" stroke-width="3.5" fill="none" stroke-linecap="round"/>
  <text x="325" y="70" font-family="Inter, sans-serif" font-size="12" font-weight="700" fill="#059669">Класс гомотопии H₁ (Оптимум)</text>

  <path d="M90,240 Q220,285 360,285 Q500,285 640,240" stroke="#94a3b8" stroke-width="2" fill="none" stroke-dasharray="4,4"/>
  <text x="325" y="305" font-family="Inter, sans-serif" font-size="11" fill="#64748b">Класс гомотопии H₂</text>

  <line x1="360" y1="128" x2="360" y2="88" stroke="#ef4444" stroke-width="2"/>
  <circle cx="360" cy="88" r="2.5" fill="#ef4444"/>
  <text x="368" y="112" font-family="JetBrains Mono" font-size="10" font-weight="700" fill="#ef4444">F_rep</text>

  <g fill="#0284c7" stroke="#ffffff" stroke-width="1.5">
'''
    pts = [(90, 240), (160, 150), (250, 95), (360, 85), (470, 95), (560, 150), (640, 240)]
    for x, y in pts:
        svg += f'    <circle cx="{x}" cy="{y}" r="5"/>\n'

    svg += f'''  </g>

  <text x="180" y="120" font-family="JetBrains Mono" font-size="9" fill="#0284c7">Δt₁</text>
  <text x="290" y="80" font-family="JetBrains Mono" font-size="9" fill="#0284c7">Δt₂</text>

  <circle cx="90" cy="240" r="8" fill="#059669" stroke="#ffffff" stroke-width="2"/>
  <text x="75" y="265" font-family="Inter" font-size="11.5" font-weight="700" fill="#059669">Старт s₀</text>

  <circle cx="640" cy="240" r="8" fill="#dc2626" stroke="#ffffff" stroke-width="2"/>
  <text x="625" y="265" font-family="Inter" font-size="11.5" font-weight="700" fill="#dc2626">Цель s_N</text>

  <rect x="30" y="275" width="260" height="65" rx="6" fill="#f8fafc" stroke="#cbd5e1" stroke-width="1"/>
  <text x="40" y="295" font-family="JetBrains Mono" font-size="10.5" font-weight="700" fill="#0f172a">V(B) = ∑ (w_t·Δt_i² + w_obs·f_obs)</text>
  <text x="40" y="315" font-family="Inter" font-size="10" fill="#64748b">Оптимизирует время проезда и кинематику</text>
  <text x="40" y="328" font-family="Inter" font-size="10" fill="#64748b">одновременно с расстоянием до преград</text>
</svg>'''

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(svg)
    print(f"Generated: {filepath}")

# -------------------------------------------------------------------------
# Diagram 10: Lecture 05 - Dubins 6 Canonical Words
# -------------------------------------------------------------------------
def generate_dubins_words():
    filepath = os.path.join(OUTPUT_DIR, 'lecture-05', 'dubins_words.svg')
    ensure_dir(filepath)

    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 360" width="100%" height="100%">
  <rect width="100%" height="100%" rx="10" fill="#ffffff" stroke="#e2e8f0" stroke-width="1.5"/>

  <g transform="translate(30, 24)">
    <text x="0" y="0" font-family="Inter, sans-serif" font-size="15" font-weight="700" fill="#0f172a">6 канонических слов Дубинса (Dubins, 1957)</text>
    <text x="0" y="18" font-family="Inter, sans-serif" font-size="11.5" fill="#64748b">Кратчайший путь для автомобиля с передней передачей (v &gt; 0, |κ| ≤ 1/R_min) состоит из 3 сегментов</text>
  </g>
'''
    words = [
        ('1. LSL (CSC)', 'Left arc → Straight → Left arc', 'M30,70 A30,30 0 0,0 60,40 L150,40 A30,30 0 0,0 180,70', True),
        ('2. RSR (CSC)', 'Right arc → Straight → Right arc', 'M30,40 A30,30 0 0,1 60,70 L150,70 A30,30 0 0,1 180,40', False),
        ('3. LSR (CSC)', 'Left arc → Straight → Right arc', 'M30,70 A30,30 0 0,0 60,40 L150,70 A30,30 0 0,1 180,40', False),
        ('4. RSL (CSC)', 'Right arc → Straight → Left arc', 'M30,40 A30,30 0 0,1 60,70 L150,40 A30,30 0 0,0 180,70', False),
        ('5. LRL (CCC)', '3 сопряженных круга максимальной кривизны', 'M30,65 A25,25 0 0,0 70,45 A25,25 0 0,1 130,45 A25,25 0 0,0 170,65', False),
        ('6. RLR (CCC)', 'Применяется при близком расположении целей', 'M30,45 A25,25 0 0,1 70,65 A25,25 0 0,0 130,65 A25,25 0 0,1 170,45', False),
    ]

    for idx, (title, desc, path_d, is_best) in enumerate(words):
        col = idx % 3
        row = idx // 3
        gx = 30 + col * 240
        gy = 65 + row * 140

        stroke_col = "#059669" if is_best else "#0284c7"
        bg_col = "#f0fdf4" if is_best else "#f8fafc"
        border_col = "#86efac" if is_best else "#e2e8f0"

        svg += f'''  <g transform="translate({gx}, {gy})">
    <rect width="225" height="125" rx="6" fill="{bg_col}" stroke="{border_col}" stroke-width="1.2"/>
    <text x="12" y="20" font-family="Inter" font-size="12" font-weight="700" fill="#0f172a">{title}</text>
    <text x="12" y="34" font-family="Inter" font-size="9.5" fill="#64748b">{desc}</text>

    <path d="{path_d}" stroke="{stroke_col}" stroke-width="2.8" fill="none" stroke-linecap="round"/>

    <circle cx="30" cy="55" r="3.5" fill="#0284c7"/>
    <circle cx="170" cy="55" r="3.5" fill="#dc2626"/>
'''
        if is_best:
            svg += '    <rect x="135" y="9" width="78" height="18" rx="3" fill="#059669"/>\n'
            svg += '    <text x="141" y="22" font-family="Inter" font-size="9.5" font-weight="700" fill="#ffffff">★ ШОРТЕСТ</text>\n'

        svg += '  </g>\n'

    svg += '</svg>'

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(svg)
    print(f"Generated: {filepath}")

# -------------------------------------------------------------------------
# Diagram 11: Lecture 05 - Reeds-Shepp Curves
# -------------------------------------------------------------------------
def generate_reeds_shepp_curves():
    filepath = os.path.join(OUTPUT_DIR, 'lecture-05', 'reeds_shepp_curves.svg')
    ensure_dir(filepath)

    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 360" width="100%" height="100%">
  <rect width="100%" height="100%" rx="10" fill="#ffffff" stroke="#e2e8f0" stroke-width="1.5"/>

  <g transform="translate(30, 24)">
    <text x="0" y="0" font-family="Inter, sans-serif" font-size="15" font-weight="700" fill="#0f172a">Кривые Ридса-Шеппа: Маневры с реверсом (Cusp)</text>
    <text x="0" y="18" font-family="Inter, sans-serif" font-size="11.5" fill="#64748b">Расширение Дубинса: допускается движение задним ходом (v &lt; 0), образующее точки возврата (точки переключения передач)</text>
  </g>

  <!-- Left: Reeds-Shepp with cusp -->
  <g transform="translate(30, 65)">
    <rect width="335" height="265" rx="8" fill="#f8fafc" stroke="#e2e8f0" stroke-width="1"/>
    <text x="16" y="24" font-family="Inter" font-size="13" font-weight="700" fill="#0f172a">1. Маневр параллельной парковки L⁺ | R⁻ | L⁺</text>

    <!-- Forward segment L+ -->
    <path d="M40,210 Q90,170 140,170" stroke="#0284c7" stroke-width="3.5" fill="none" stroke-linecap="round"/>
    <text x="60" y="175" font-family="JetBrains Mono" font-size="11" font-weight="700" fill="#0284c7">L⁺ (Вперед)</text>

    <circle cx="140" cy="170" r="6" fill="#d97706" stroke="#ffffff" stroke-width="2"/>
    <text x="110" y="150" font-family="Inter" font-size="10" font-weight="700" fill="#d97706">Точка возврата (Cusp)</text>

    <!-- Reverse segment R- -->
    <path d="M140,170 Q190,170 230,120" stroke="#dc2626" stroke-width="3.5" fill="none" stroke-linecap="round" stroke-dasharray="4,2"/>
    <text x="195" y="160" font-family="JetBrains Mono" font-size="11" font-weight="700" fill="#dc2626">R⁻ (Назад)</text>

    <circle cx="230" cy="120" r="6" fill="#d97706" stroke="#ffffff" stroke-width="2"/>

    <!-- Forward segment L+ to goal -->
    <path d="M230,120 Q270,80 300,80" stroke="#0284c7" stroke-width="3.5" fill="none" stroke-linecap="round"/>
    <text x="260" y="70" font-family="JetBrains Mono" font-size="11" font-weight="700" fill="#0284c7">L⁺</text>

    <circle cx="300" cy="80" r="6" fill="#059669"/>
    <text x="290" y="105" font-family="Inter" font-size="11" font-weight="700" fill="#059669">Цель</text>

    <rect x="14" y="210" width="307" height="42" rx="4" fill="#fffbeb" stroke="#fef08a" stroke-width="1"/>
    <text x="22" y="228" font-family="Inter" font-size="10.5" font-weight="700" fill="#854d0e">В точке cusp скорость v меняет знак:</text>
    <text x="22" y="242" font-family="Inter" font-size="10" fill="#b45309">Робот останавливается, выворачивает руль и дает задний ход</text>
  </g>

  <!-- Right: 48 Optimal Words -->
  <g transform="translate(395, 65)">
    <rect width="335" height="265" rx="8" fill="#f8fafc" stroke="#e2e8f0" stroke-width="1"/>
    <text x="16" y="24" font-family="Inter" font-size="13" font-weight="700" fill="#0f172a">2. Семейства Ридса-Шеппа (48 слов / 9 типов)</text>

    <g transform="translate(16, 45)" font-family="JetBrains Mono" font-size="10" fill="#334155">
      <rect x="0" y="0" width="303" height="26" fill="#f1f5f9" rx="3"/>
      <text x="8" y="17" font-weight="700">1. C | C | C</text> <text x="160" y="17" fill="#64748b">L⁺ R⁻ L⁺, R⁺ L⁻ R⁺</text>

      <rect x="0" y="32" width="303" height="26" fill="#ffffff" rx="3"/>
      <text x="8" y="49" font-weight="700">2. C | C C</text> <text x="160" y="49" fill="#64748b">L⁺ | R⁻ L⁻, R⁺ | L⁻ R⁻</text>

      <rect x="0" y="64" width="303" height="26" fill="#f1f5f9" rx="3"/>
      <text x="8" y="81" font-weight="700">3. C S C</text> <text x="160" y="81" fill="#64748b">L⁺ S⁺ L⁺, R⁺ S⁺ R⁺</text>

      <rect x="0" y="96" width="303" height="26" fill="#ffffff" rx="3"/>
      <text x="8" y="113" font-weight="700">4. C | S C</text> <text x="160" y="113" fill="#64748b">L⁺ | S⁻ L⁻, R⁺ | S⁻ R⁻</text>

      <rect x="0" y="128" width="303" height="26" fill="#f1f5f9" rx="3"/>
      <text x="8" y="145" font-weight="700">5. C | C_u C_u | C</text> <text x="160" y="145" fill="#64748b">Спецманевры разворота</text>
    </g>

    <rect x="14" y="210" width="307" height="42" rx="4" fill="#eff6ff" stroke="#bfdbfe" stroke-width="1"/>
    <text x="22" y="228" font-family="Inter" font-size="10.5" font-weight="700" fill="#1e40af">Используется в Hybrid A* (Stanford Junior):</text>
    <text x="22" y="242" font-family="Inter" font-size="10" fill="#1d4ed8">Аналитический шоткат к цели для парковки в гаражах</text>
  </g>
</svg>'''

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(svg)
    print(f"Generated: {filepath}")

# -------------------------------------------------------------------------
# Diagram 12: Lecture 06 - Receding Horizon MPC
# -------------------------------------------------------------------------
def generate_receding_horizon():
    filepath = os.path.join(OUTPUT_DIR, 'lecture-06', 'receding_horizon.svg')
    ensure_dir(filepath)

    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 360" width="100%" height="100%">
  <rect width="100%" height="100%" rx="10" fill="#ffffff" stroke="#e2e8f0" stroke-width="1.5"/>

  <g transform="translate(30, 24)">
    <text x="0" y="0" font-family="Inter, sans-serif" font-size="15" font-weight="700" fill="#0f172a">Принцип скользящего горизонта MPC (Receding Horizon)</text>
    <text x="0" y="18" font-family="Inter, sans-serif" font-size="11.5" fill="#64748b">Оптимизация на горизонте N шагов, выполнение ТОЛЬКО первого действия u_0 и сдвиг окна на t + 1</text>
  </g>

  <line x1="50" y1="260" x2="710" y2="260" stroke="#94a3b8" stroke-width="1.5"/>
  <text x="715" y="264" font-family="JetBrains Mono" font-size="11" fill="#64748b">Время t</text>

  <rect x="230" y="75" width="320" height="200" fill="#eff6ff" fill-opacity="0.6" stroke="#3b82f6" stroke-width="1.8" rx="6"/>
  <text x="240" y="95" font-family="Inter" font-size="12" font-weight="700" fill="#1d4ed8">Горизонт предсказания (Prediction Horizon N)</text>

  <path d="M60,210 Q140,230 230,190" stroke="#64748b" stroke-width="2.5" fill="none"/>
  <text x="90" y="240" font-family="Inter" font-size="10.5" fill="#64748b">Прошлые состояния (t &lt; t₀)</text>

  <circle cx="230" cy="190" r="7" fill="#0284c7" stroke="#ffffff" stroke-width="2"/>
  <text x="210" y="215" font-family="JetBrains Mono" font-size="11" font-weight="700" fill="#0284c7">x(t₀)</text>
  <line x1="230" y1="260" x2="230" y2="190" stroke="#0284c7" stroke-width="1.5" stroke-dasharray="3,3"/>
  <text x="220" y="280" font-family="JetBrains Mono" font-size="11" font-weight="700" fill="#0284c7">t₀</text>

  <path d="M230,190 Q340,120 550,130" stroke="#94a3b8" stroke-width="2" stroke-dasharray="4,4" fill="none"/>
  <text x="460" y="115" font-family="Inter" font-size="10" fill="#64748b">x_ref (Опорная траектория)</text>

  <path d="M230,190 Q320,150 420,145 T550,135" stroke="#059669" stroke-width="3" fill="none"/>
  <circle cx="300" cy="162" r="4.5" fill="#059669"/>
  <circle cx="380" cy="148" r="4.5" fill="#059669"/>
  <circle cx="470" cy="140" r="4.5" fill="#059669"/>
  <circle cx="550" cy="135" r="5" fill="#059669"/>
  <text x="350" y="170" font-family="Inter" font-size="11" font-weight="700" fill="#059669">Прогноз x_{{t+k|t}}</text>

  <g transform="translate(230, 190)">
    <line x1="0" y1="0" x2="70" y2="-28" stroke="#dc2626" stroke-width="3" stroke-linecap="round"/>
    <polygon points="70,-28 60,-32 62,-23" fill="#dc2626"/>
    <text x="15" y="-20" font-family="JetBrains Mono" font-size="11" font-weight="700" fill="#dc2626">u₀* (Выполняется!)</text>
  </g>

  <line x1="550" y1="260" x2="550" y2="75" stroke="#3b82f6" stroke-width="1.5" stroke-dasharray="3,3"/>
  <text x="535" y="280" font-family="JetBrains Mono" font-size="11" font-weight="700" fill="#1e40af">t₀ + N</text>

  <g transform="translate(270, 305)">
    <path d="M0,0 H120 M110,-5 L120,0 L110,5" stroke="#0284c7" stroke-width="2.5" fill="none"/>
    <text x="15" y="-8" font-family="Inter" font-size="11" font-weight="700" fill="#0284c7">Сдвиг окна на t₀ + 1 с обратной связью</text>
  </g>
</svg>'''

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(svg)
    print(f"Generated: {filepath}")

# -------------------------------------------------------------------------
# Diagram 13: Lecture 06 - MPC Real-Time Iteration (RTI) Pipeline
# -------------------------------------------------------------------------
def generate_mpc_qp_pipeline():
    filepath = os.path.join(OUTPUT_DIR, 'lecture-06', 'mpc_qp_pipeline.svg')
    ensure_dir(filepath)

    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 360" width="100%" height="100%">
  <rect width="100%" height="100%" rx="10" fill="#ffffff" stroke="#e2e8f0" stroke-width="1.5"/>

  <g transform="translate(30, 24)">
    <text x="0" y="0" font-family="Inter, sans-serif" font-size="15" font-weight="700" fill="#0f172a">Архитектура контура RTI (Real-Time Iteration, Diehl et al.)</text>
    <text x="0" y="18" font-family="Inter, sans-serif" font-size="11.5" fill="#64748b">Разделение фаз вычислений для минимизации задержки обратной связи (Feedback Latency &lt; 1 мс)</text>
  </g>

  <g transform="translate(30, 75)">
    <rect width="400" height="240" rx="8" fill="#eff6ff" stroke="#3b82f6" stroke-width="1.5"/>
    <rect width="400" height="32" rx="8" fill="#3b82f6"/>
    <text x="14" y="21" font-family="Inter" font-size="12.5" font-weight="700" fill="#ffffff">Фаза подготовки (Preparation Phase) ~ 10–30 мс</text>

    <g transform="translate(16, 50)" font-family="Inter" font-size="11.5" fill="#334155">
      <text x="0" y="0" font-weight="700">• Выполняется ДО поступления нового замера состояния</text>
      <text x="0" y="24">• Линеаризация нелинейной динамики робота f(x, u)</text>
      <text x="0" y="48">• Расчет матриц чувствительности: A_k = ∂f/∂x, B_k = ∂f/∂u</text>
      <text x="0" y="72">• Формирование гессиана H и конденсация QP-задачи</text>
      <text x="0" y="96">• Факторизация Холецкого (H = L L^T) или qpOASES / OSQP init</text>

      <rect x="0" y="115" width="368" height="42" rx="4" fill="#dbeafe"/>
      <text x="10" y="133" font-family="JetBrains Mono" font-size="10.5" fill="#1e40af">H = B^T Q B + R,  g = B^T Q (A x_ref)</text>
      <text x="10" y="148" font-family="Inter" font-size="10" fill="#1e40af">Тяжелая матричная алгебра завершена заранее!</text>
    </g>
  </g>

  <g transform="translate(455, 75)">
    <rect width="275" height="240" rx="8" fill="#f0fdf4" stroke="#10b981" stroke-width="1.5"/>
    <rect width="275" height="32" rx="8" fill="#10b981"/>
    <text x="14" y="21" font-family="Inter" font-size="12.5" font-weight="700" fill="#ffffff">Фаза отклика (Feedback) &lt; 1 мс</text>

    <g transform="translate(16, 50)" font-family="Inter" font-size="11.5" fill="#334155">
      <text x="0" y="0" font-weight="700" fill="#065f46">⚡ Триггер: пришел замер x(t₀)</text>
      <text x="0" y="24">• Обновление вектора градиента:</text>
      <text x="12" y="42" font-family="JetBrains Mono" font-size="10.5" fill="#047857">g_k = f(x(t₀) - x_ref)</text>
      <text x="0" y="66">• ОДНА итерация решения QP:</text>
      <text x="12" y="84" font-family="JetBrains Mono" font-size="10.5" fill="#047857">min 1/2 Δu^T H Δu + g^T Δu</text>
      <text x="0" y="108">• Немедленная выдача u₀* на моторы</text>

      <rect x="0" y="125" width="243" height="45" rx="4" fill="#bbf7d0"/>
      <text x="10" y="144" font-family="Inter" font-size="11" font-weight="700" fill="#065f46">Задержка обратной связи:</text>
      <text x="10" y="160" font-family="JetBrains Mono" font-size="11" font-weight="700" fill="#047857">Latency &lt; 200–500 мкс!</text>
    </g>
  </g>

  <g transform="translate(427, 180)">
    <path d="M0,0 H24 M16,-5 L24,0 L16,5" stroke="#059669" stroke-width="3" fill="none"/>
  </g>
</svg>'''

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(svg)
    print(f"Generated: {filepath}")

# -------------------------------------------------------------------------
# Diagram 14: Lecture 07 - Ackermann Steering & Bicycle Kinematics
# -------------------------------------------------------------------------
def generate_car_kinematics_ackermann():
    filepath = os.path.join(OUTPUT_DIR, 'lecture-07', 'car_kinematics_ackermann.svg')
    ensure_dir(filepath)

    icr = (140, 60)

    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 360" width="100%" height="100%">
  <rect width="100%" height="100%" rx="10" fill="#ffffff" stroke="#e2e8f0" stroke-width="1.5"/>

  <g transform="translate(30, 24)">
    <text x="0" y="0" font-family="Inter, sans-serif" font-size="15" font-weight="700" fill="#0f172a">Кинематика велосипеда и геометрия руления Аккермана</text>
    <text x="0" y="18" font-family="Inter, sans-serif" font-size="11.5" fill="#64748b">Все колеса катятся без бокового проскальзывания вокруг общего Мгновенного Центра Вращения (ICR)</text>
  </g>

  <circle cx="{icr[0]}" cy="{icr[1]}" r="7" fill="#dc2626" stroke="#ffffff" stroke-width="2"/>
  <text x="{icr[0]-15}" y="{icr[1]-12}" font-family="Inter" font-size="12" font-weight="700" fill="#dc2626">ICR (МЦВ)</text>

  <g transform="translate(360, 180)">
    <rect x="-40" y="-80" width="80" height="160" rx="8" fill="#f8fafc" stroke="#334155" stroke-width="2"/>

    <line x1="-50" y1="50" x2="50" y2="50" stroke="#0f172a" stroke-width="3"/>
    <rect x="-56" y="32" width="12" height="36" rx="2" fill="#1e293b"/>
    <rect x="44" y="32" width="12" height="36" rx="2" fill="#1e293b"/>
    <text x="-35" y="70" font-family="Inter" font-size="10" fill="#64748b">Задний мост</text>

    <line x1="-50" y1="-50" x2="50" y2="-50" stroke="#0f172a" stroke-width="3"/>
    <g transform="translate(-48, -50) rotate(-34)">
      <rect x="-6" y="-18" width="12" height="36" rx="2" fill="#0284c7"/>
    </g>
    <g transform="translate(48, -50) rotate(-23)">
      <rect x="-6" y="-18" width="12" height="36" rx="2" fill="#0284c7"/>
    </g>

    <line x1="68" y1="-50" x2="68" y2="50" stroke="#94a3b8" stroke-width="1.2"/>
    <text x="74" y="5" font-family="JetBrains Mono" font-size="11" font-weight="700" fill="#475569">База L</text>
    <line x1="-48" y1="-95" x2="48" y2="-95" stroke="#94a3b8" stroke-width="1.2"/>
    <text x="-15" y="-102" font-family="JetBrains Mono" font-size="11" font-weight="700" fill="#475569">Колея W</text>
  </g>

  <line x1="{icr[0]}" y1="{icr[1]}" x2="360" y2="230" stroke="#dc2626" stroke-width="1.5" stroke-dasharray="3,3"/>
  <line x1="{icr[0]}" y1="{icr[1]}" x2="312" y2="130" stroke="#0284c7" stroke-width="1.5" stroke-dasharray="3,3"/>
  <line x1="{icr[0]}" y1="{icr[1]}" x2="408" y2="130" stroke="#0284c7" stroke-width="1.5" stroke-dasharray="3,3"/>

  <g transform="translate(480, 80)">
    <rect width="250" height="230" rx="8" fill="#f8fafc" stroke="#e2e8f0" stroke-width="1"/>
    <text x="14" y="24" font-family="Inter" font-size="13" font-weight="700" fill="#0f172a">Условие Аккермана:</text>
    <rect x="12" y="36" width="226" height="38" rx="4" fill="#eff6ff" stroke="#bfdbfe" stroke-width="1"/>
    <text x="20" y="60" font-family="JetBrains Mono" font-size="12" font-weight="700" fill="#1e40af">cot δ_out - cot δ_in = W / L</text>

    <text x="14" y="100" font-family="Inter" font-size="11.5" font-weight="700" fill="#0f172a">Эквивалент: модель велосипеда</text>
    <text x="14" y="122" font-family="JetBrains Mono" font-size="11" fill="#0284c7">tan δ = L / R</text>
    <text x="14" y="142" font-family="Inter" font-size="10.5" fill="#475569">• δ — угол виртуального переднего колеса</text>
    <text x="14" y="160" font-family="Inter" font-size="10.5" fill="#475569">• R — радиус поворота задней оси</text>
    <text x="14" y="178" font-family="Inter" font-size="10.5" fill="#475569">• Неголономная связь: dy/dx = tan θ</text>

    <rect x="12" y="195" width="226" height="24" rx="3" fill="#ecfdf5"/>
    <text x="18" y="211" font-family="JetBrains Mono" font-size="10" font-weight="700" fill="#059669">v_lateral = ẏ cos θ - ẋ sin θ = 0</text>
  </g>
</svg>'''

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(svg)
    print(f"Generated: {filepath}")

# -------------------------------------------------------------------------
# Diagram 15: Lecture 07 - Lie Bracket Commutator
# -------------------------------------------------------------------------
def generate_lie_bracket_commutator():
    filepath = os.path.join(OUTPUT_DIR, 'lecture-07', 'lie_bracket_commutator.svg')
    ensure_dir(filepath)

    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 360" width="100%" height="100%">
  <rect width="100%" height="100%" rx="10" fill="#ffffff" stroke="#e2e8f0" stroke-width="1.5"/>

  <g transform="translate(30, 24)">
    <text x="0" y="0" font-family="Inter, sans-serif" font-size="15" font-weight="700" fill="#0f172a">Скобка Ли [f₁, f₂]: Геометрия параллельной парковки</text>
    <text x="0" y="18" font-family="Inter, sans-serif" font-size="11.5" fill="#64748b">Коммутатор потоков векторных полей порождает движение в запрещенном направлении (дрейф вбок!)</text>
  </g>

  <g transform="translate(40, 70)">
    <rect width="400" height="245" rx="8" fill="#f8fafc" stroke="#e2e8f0" stroke-width="1"/>

    <path d="M60,190 H220" stroke="#0284c7" stroke-width="3" stroke-linecap="round"/>
    <polygon points="220,190 210,185 210,195" fill="#0284c7"/>
    <text x="110" y="210" font-family="JetBrains Mono" font-size="11" font-weight="700" fill="#0284c7">1. +f₁ (Вперед)</text>

    <path d="M220,190 Q240,160 220,110" stroke="#2563eb" stroke-width="3" stroke-linecap="round"/>
    <polygon points="220,110 228,118 220,125" fill="#2563eb"/>
    <text x="240" y="150" font-family="JetBrains Mono" font-size="11" font-weight="700" fill="#2563eb">2. +f₂ (Руль)</text>

    <path d="M220,110 H80" stroke="#dc2626" stroke-width="3" stroke-linecap="round"/>
    <polygon points="80,110 90,105 90,115" fill="#dc2626"/>
    <text x="120" y="95" font-family="JetBrains Mono" font-size="11" font-weight="700" fill="#dc2626">3. -f₁ (Назад)</text>

    <path d="M80,110 Q60,130 60,145" stroke="#9333ea" stroke-width="3" stroke-linecap="round"/>
    <text x="10" y="130" font-family="JetBrains Mono" font-size="11" font-weight="700" fill="#9333ea">4. -f₂ (Руль)</text>

    <line x1="60" y1="190" x2="60" y2="145" stroke="#059669" stroke-width="4" stroke-linecap="round"/>
    <polygon points="60,145 55,155 65,155" fill="#059669"/>
    
    <circle cx="60" cy="190" r="5" fill="#0f172a"/>
    <text x="35" y="208" font-family="Inter" font-size="11" font-weight="700" fill="#0f172a">Старт</text>

    <circle cx="60" cy="145" r="5" fill="#059669"/>
    <text x="72" y="165" font-family="Inter" font-size="12" font-weight="700" fill="#059669">Дрейф вбок! ε²·[f₁, f₂]</text>
  </g>

  <g transform="translate(465, 70)">
    <rect width="265" height="245" rx="8" fill="#f8fafc" stroke="#e2e8f0" stroke-width="1"/>
    <text x="14" y="24" font-family="Inter" font-size="13" font-weight="700" fill="#0f172a">Теорема Чоу-Рашевского:</text>
    <rect x="12" y="36" width="241" height="48" rx="4" fill="#ecfdf5" stroke="#a7f3d0" stroke-width="1"/>
    <text x="18" y="56" font-family="JetBrains Mono" font-size="11" font-weight="700" fill="#065f46">[f₁, f₂] = ∂f₂/∂x f₁ - ∂f₁/∂x f₂</text>
    <text x="18" y="72" font-family="JetBrains Mono" font-size="11" font-weight="700" fill="#047857">rank Δ_LARC = dim(C) = 3</text>

    <text x="14" y="110" font-family="Inter" font-size="11.5" fill="#334155">• Автомобиль имеет только 2 привода: тяга (f₁) и руление (f₂).</text>
    <text x="14" y="145" font-family="Inter" font-size="11.5" fill="#334155">• Непосредственно ехать боком колеса не могут (чистое качение).</text>
    <text x="14" y="180" font-family="Inter" font-size="11.5" fill="#334155">• Но скобка Ли [f₁, f₂] дает ненулевую составляющую в направлении оси Y!</text>

    <rect x="12" y="210" width="241" height="24" rx="3" fill="#eff6ff"/>
    <text x="18" y="226" font-family="Inter" font-size="10" font-weight="700" fill="#1e40af">Полная управляемость системы доказана!</text>
  </g>
</svg>'''

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(svg)
    print(f"Generated: {filepath}")

# -------------------------------------------------------------------------
# Diagram 16: Lecture 08 - Real-Time Stack Hierarchy
# -------------------------------------------------------------------------
def generate_realtime_stack_hierarchy():
    filepath = os.path.join(OUTPUT_DIR, 'lecture-08', 'realtime_stack_hierarchy.svg')
    ensure_dir(filepath)

    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 360" width="100%" height="100%">
  <rect width="100%" height="100%" rx="10" fill="#ffffff" stroke="#e2e8f0" stroke-width="1.5"/>

  <g transform="translate(30, 24)">
    <text x="0" y="0" font-family="Inter, sans-serif" font-size="15" font-weight="700" fill="#0f172a">Многотактовая архитектура реального времени (1 Гц — 1000 Гц)</text>
    <text x="0" y="18" font-family="Inter, sans-serif" font-size="11.5" fill="#64748b">Иерархия контуров управления робота от жесткого RT на микроконтроллере до планирования миссии</text>
  </g>
'''
    layers = [
        ('1000 Гц (1 мс)', 'CAN / EtherCAT / Инверторы моторов', 'Токовый контур, FOC, ШИМ, энкодеры колес. Жесткий RT, джиттер < 20 мкс', '#fee2e2', '#ef4444', '#991b1b'),
        ('100 Гц (10 мс)', 'IMU / Комплементарный фильтр / EKF', 'Одометрия, слияние сенсоров, защита от опрокидывания шасси', '#ffedd5', '#f97316', '#9a3412'),
        ('20–50 Гц (20–50 мс)', 'Локальный планировщик (MPC / TEB / DWA)', 'Уклонение от динамических преград, расчет ускорений, трекинг пути', '#fef9c3', '#eab308', '#854d0e'),
        ('1–5 Гц (0.2–1 с)', 'Глобальный планировщик (A* / Nav2 / GVD)', 'Построение маршрута по статической карте, Dijkstra, Costmaps', '#eff6ff', '#3b82f6', '#1e40af'),
        ('0.1–1 Гц (1–10 с)', 'Диспетчер миссии (Behavior Tree / FSM)', 'Выбор целей, перезапуск упавших нод, взаимодействие с флотом', '#f0fdf4', '#10b981', '#065f46')
    ]

    for i, (freq, title, desc, bg, border, text_col) in enumerate(layers):
        y = 65 + i * 54
        svg += f'''  <g transform="translate(30, {y})">
    <rect width="700" height="46" rx="6" fill="{bg}" stroke="{border}" stroke-width="1.2"/>
    <rect x="0" y="0" width="140" height="46" rx="6" fill="{border}"/>
    <text x="12" y="28" font-family="JetBrains Mono" font-size="12" font-weight="700" fill="#ffffff">{freq}</text>
    <text x="155" y="20" font-family="Inter" font-size="12.5" font-weight="700" fill="{text_col}">{title}</text>
    <text x="155" y="37" font-family="Inter" font-size="10.5" fill="#475569">{desc}</text>
  </g>
'''

    svg += '</svg>'

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(svg)
    print(f"Generated: {filepath}")

# -------------------------------------------------------------------------
# Diagram 17: Lecture 08 - ROS 2 Nav2 Behavior Tree
# -------------------------------------------------------------------------
def generate_nav2_bt_tree():
    filepath = os.path.join(OUTPUT_DIR, 'lecture-08', 'nav2_bt_tree.svg')
    ensure_dir(filepath)

    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 360" width="100%" height="100%">
  <rect width="100%" height="100%" rx="10" fill="#ffffff" stroke="#e2e8f0" stroke-width="1.5"/>

  <g transform="translate(30, 24)">
    <text x="0" y="0" font-family="Inter, sans-serif" font-size="15" font-weight="700" fill="#0f172a">Архитектура ROS 2 Nav2: Дерево Поведения (Behavior Tree)</text>
    <text x="0" y="18" font-family="Inter, sans-serif" font-size="11.5" fill="#64748b">Иерархическое управление навигацией: Sequence (->), Fallback (?) и Recovery ветки</text>
  </g>

  <g transform="translate(340, 60)">
    <circle cx="20" cy="20" r="20" fill="#fef3c7" stroke="#d97706" stroke-width="2"/>
    <text x="14" y="26" font-family="Inter" font-size="18" font-weight="700" fill="#b45309">?</text>
    <text x="-25" y="52" font-family="Inter" font-size="11" font-weight="700" fill="#0f172a">Root Fallback</text>
  </g>

  <line x1="340" y1="90" x2="220" y2="135" stroke="#94a3b8" stroke-width="2"/>
  <line x1="380" y1="90" x2="500" y2="135" stroke="#94a3b8" stroke-width="2"/>

  <g transform="translate(200, 135)">
    <rect x="0" y="0" width="40" height="40" rx="6" fill="#dbeafe" stroke="#2563eb" stroke-width="2"/>
    <text x="11" y="26" font-family="Inter" font-size="18" font-weight="700" fill="#1d4ed8">→</text>
    <text x="-35" y="54" font-family="Inter" font-size="11" font-weight="700" fill="#0f172a">NavigateSequence</text>
  </g>

  <g transform="translate(480, 135)">
    <circle cx="20" cy="20" r="20" fill="#fee2e2" stroke="#dc2626" stroke-width="2"/>
    <text x="14" y="26" font-family="Inter" font-size="18" font-weight="700" fill="#b91c1c">?</text>
    <text x="-15" y="54" font-family="Inter" font-size="11" font-weight="700" fill="#dc2626">Recovery</text>
  </g>

  <line x1="200" y1="185" x2="110" y2="225" stroke="#94a3b8" stroke-width="1.8"/>
  <line x1="240" y1="185" x2="290" y2="225" stroke="#94a3b8" stroke-width="1.8"/>

  <g transform="translate(45, 225)">
    <rect width="130" height="42" rx="6" fill="#f0fdf4" stroke="#059669" stroke-width="1.8"/>
    <text x="10" y="20" font-family="Inter" font-size="10.5" font-weight="700" fill="#065f46">ComputePathToPose</text>
    <text x="10" y="34" font-family="JetBrains Mono" font-size="9" fill="#047857">Global Planner</text>
  </g>

  <g transform="translate(230, 225)">
    <rect width="125" height="42" rx="6" fill="#f0fdf4" stroke="#059669" stroke-width="1.8"/>
    <text x="25" y="20" font-family="Inter" font-size="10.5" font-weight="700" fill="#065f46">FollowPath</text>
    <text x="15" y="34" font-family="JetBrains Mono" font-size="9" fill="#047857">Local Controller</text>
  </g>

  <line x1="480" y1="185" x2="430" y2="225" stroke="#94a3b8" stroke-width="1.8"/>
  <line x1="500" y1="185" x2="545" y2="225" stroke="#94a3b8" stroke-width="1.8"/>
  <line x1="520" y1="185" x2="660" y2="225" stroke="#94a3b8" stroke-width="1.8"/>

  <g transform="translate(375, 225)">
    <rect width="105" height="42" rx="6" fill="#fff1f2" stroke="#e11d48" stroke-width="1.5"/>
    <text x="10" y="20" font-family="Inter" font-size="10" font-weight="700" fill="#9f1239">ClearCostmap</text>
    <text x="10" y="34" font-family="JetBrains Mono" font-size="8.5" fill="#e11d48">Сброс вокселей</text>
  </g>

  <g transform="translate(495, 225)">
    <rect width="95" height="42" rx="6" fill="#fff1f2" stroke="#e11d48" stroke-width="1.5"/>
    <text x="18" y="20" font-family="Inter" font-size="10" font-weight="700" fill="#9f1239">Spin (360°)</text>
    <text x="10" y="34" font-family="JetBrains Mono" font-size="8.5" fill="#e11d48">Осмотр сенсорами</text>
  </g>

  <g transform="translate(605, 225)">
    <rect width="105" height="42" rx="6" fill="#fff1f2" stroke="#e11d48" stroke-width="1.5"/>
    <text x="22" y="20" font-family="Inter" font-size="10" font-weight="700" fill="#9f1239">BackUp (Откат)</text>
    <text x="12" y="34" font-family="JetBrains Mono" font-size="8.5" fill="#e11d48">Выход из тупика</text>
  </g>

  <g transform="translate(30, 310)" font-family="Inter" font-size="10.5">
    <circle cx="8" cy="8" r="5" fill="#059669"/>
    <text x="20" y="12" font-weight="600" fill="#065f46">SUCCESS (Успех)</text>

    <circle cx="160" cy="8" r="5" fill="#3b82f6"/>
    <text x="172" y="12" font-weight="600" fill="#1e40af">RUNNING (В процессе)</text>

    <circle cx="320" cy="8" r="5" fill="#dc2626"/>
    <text x="332" y="12" font-weight="600" fill="#991b1b">FAILURE (Сбой → переход к Recovery)</text>
  </g>
</svg>'''

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(svg)
    print(f"Generated: {filepath}")

def main():
    print("=== Generating Rigorous Algorithmic Diagrams ===")
    generate_visibility_vs_voronoi()
    generate_theta_star_los()
    generate_minkowski_cspace()
    generate_sdf_gradient()
    generate_rrt_star_rewire()
    generate_informed_rrt_ellipse()
    generate_apf_u_trap()
    generate_dwa_space()
    generate_teb_elastic_band()
    generate_dubins_words()
    generate_reeds_shepp_curves()
    generate_receding_horizon()
    generate_mpc_qp_pipeline()
    generate_car_kinematics_ackermann()
    generate_lie_bracket_commutator()
    generate_realtime_stack_hierarchy()
    generate_nav2_bt_tree()
    print("=== All Algorithmic Diagrams Successfully Generated! ===")

if __name__ == '__main__':
    main()
